### ISSUE TITLE
[BUG] - PAX LOAD selector doesn't work

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1267] opened 2024-05-27 20:47 UTC
### Describe the bug

The PAX LOAD selector cannot be changed by any method I can find

### Steps to reproduce

Try to change it using any combination of input methods.

### Expected behaviour

Per the FCOM:
![image](https://github.com/invernyx/md11-bugs/assets/7919184/821eee40-2fa9-4870-8aac-59d2e3438e01)
It looks like the default value should also not be 000 as it currently is.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0agl

### Agreement

- [X] Yes

**Comment by turbofandude** [comment] 2024-05-27 21:38
Duplicate of https://github.com/invernyx/md11-bugs/issues/469

**Closed by turbofandude** 2024-05-27 21:38 UTC
Labels: type: bug, sys: core
