### ISSUE TITLE
[BUG] - Nose Gear Cocked?

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#111] opened 2023-10-25 09:58 UTC
### Describe the bug

Nose gear cocked 90 degrees when airborne and configured. More thana visual glitch, because the aircraft pulled hard upon nose gear touchdown.

### Steps to reproduce

Put the gear down.

### Expected behaviour

NG should be straight.

### Evidence

i'll get one next flight

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by Jishwaah** [comment] 2023-10-25 12:52
@017941 Can you please elaborate further on what the issue is, when it happens, and the exact steps to reproduce it? Has it happened once, or does it repeat?

**Comment by 017941** [comment] 2023-10-25 14:53
Hi Joshua. The nose gear, when viewed from the outside, is cocked 90 degrees. I would say that this is a visual glitch, but the airplane did kick right when landing and the nose wheel straightened immediately. I had the replay camera on, and viewed the condition from outside. This has happened on three consecutive approaches.

**Comment by 017941** [comment] 2023-10-25 15:20
https://clipchamp.com/watch/EDfj56HKJEw

video link for cocked nosegear
________________________________

**Comment by 017941** [comment] 2023-10-25 15:23
________________________________

**Comment by 017941** [comment] 2023-10-25 15:26
[cid:5a067605-5b17-40b1-8931-d13a88840f12]
________________________________

**Comment by 017941** [comment] 2023-10-25 18:32
https://youtube.com/watch?v=bcQRrxQm4VU&si=xkYsY-zldN6GtVLlSent from my iPadSent from my iPadOn Oct 25, 2023, at 11:26 AM, Jeffrey Richard ***@***.***> wrote:﻿





<image.png>

**Comment by 017941** [comment] 2023-11-01 17:29
The nose gear is turned full to the left every time I put the gear down. I has been occurring since 7.0

**Comment by GenericNerd** [comment] 2023-11-01 22:56
This is a known issue, as stated on the home page of this repository :)

**Comment by GenericNerd** [comment] 2023-11-14 19:52
This should hopefully be fixed in the next release. If it isn't, please open up a new issue and refer to #111

**Closed by GenericNerd** 2023-11-14 19:52 UTC
Labels: type: bug, sys: visual
