### ISSUE TITLE
[BUG] - Warning lights on, but operating normally

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#552] opened 2023-11-15 17:09 UTC
### Describe the bug

Fuel warning lights are on on the overhead.

### Steps to reproduce

Not sure. This is my first flight on the new build. Could be user error, but this wasn't an issue on the previous build. 

### Expected behaviour

Warning lights on the TRANS lights saying LOW, APU ENG AIR, AVNCS FAN FLOW OVRD, TRIM AIR AVNCS OVHT, DUMP ON, MANF DRAIN, FUEL DUMP EMER STOP, GALLY BUS 1 thru 3 OFF

### Evidence

https://imgur.com/hx92LtW

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

All phases of flight

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-15 21:45
did you do the annunciator light test before this by chance?

**Comment by CptUnicorn** [comment] 2023-11-15 21:47
> did you do the annunciator light test before this by chance?

I did yes.

**Comment by TheFightingRaven** [comment] 2023-11-15 22:07
in that case it a duplicate of #357

**Closed by TheFightingRaven** 2023-11-15 22:07 UTC
Labels: type: duplicate, type: verification required, info: more info required, sys: core
