### ISSUE TITLE
[BUG] - MCDU CLR button continues clearing for ~3sec

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#89] opened 2023-10-21 23:10 UTC
### Describe the bug

After pressing CLR to clear anything on the MCDU, it continues clearing the scratchpad for approx. 3 sec

### Steps to reproduce

Press CLR to clear any entered data
Press a number/letter into the scratchpad within 3sec, it will also be cleared.

### Expected behaviour

If scratchpad is empty, CLR clears previously entered data in MCDU.
If scratchpad has data, CLR removes data
Data should be immediately enterable in scratchpad.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

NA

### Agreement

- [X] Yes

**Comment by turbofandude** [comment] 2023-10-31 17:55
I know that this does happen, but I cannot recreate this. I think it may be due to how quickly the mouse moves away from the CLR button or similar - are you able to find a commonality?

**Comment by GenericNerd** [comment] 2023-11-01 23:54
Duplicate of #24

**Closed by GenericNerd** 2023-11-01 23:54 UTC
Labels: type: bug, type: duplicate, sys: fms
