### ISSUE TITLE
[BUG] - Impossible to type a ZFW that beigns with a 3

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1259] opened 2024-05-27 19:56 UTC
### Describe the bug

It's impossible to type a ZFW that starts with a 3 because the number just repopulates 

### Steps to reproduce

![FlightSimulator_mZzLQmyiR3-ezgif com-optimize(2)](https://github.com/invernyx/md11-bugs/assets/7919184/d3c9c623-06cd-4737-996c-d30f89c32728)
As you can see in the gif, every time I backspace the leading character the field just resets to the minimum value, preventing me from actually typing any number that starts with anything other than 2.

### Expected behaviour

You should be able to type any number, but the number should be clamped to prevent illogical values.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2024-05-27 20:20
Duplicate of #1208

**Closed by GenericNerd** 2024-05-27 20:20 UTC
Labels: type: bug, type: duplicate, sys: supporting system
