### ISSUE TITLE
[TODO] - MD11F missing exit sign

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#471] opened 2023-11-11 23:22 UTC
### Describe the bug

No exit text

### Steps to reproduce

Load up the F & Look at D1L from inside 

### Expected behaviour

To have exit text 

### Evidence

![Screenshot_11](https://github.com/invernyx/md11-bugs/assets/70169249/0fa9f774-89c2-4cdf-bf81-2741641a2a4d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment] 2024-01-02 20:39
This is a duplicate of issue [#284.](https://github.com/invernyx/md11-bugs/issues/284)

**Closed by arwasairl** 2024-01-02 20:39 UTC
Labels: sys: visual, type: todo
