### ISSUE TITLE
[BUG] - descend Forecast page isn`t working

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#418] opened 2023-11-10 13:34 UTC
### Describe the bug

The descend forecast page isn`t working

### Steps to reproduce

When clicking on the forecast page and try to open it it isn`t responding

### Expected behaviour

Hope to see this coming

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Descent

### Altitude

0

### Departure

0

### Arrival

0

### Cruise level

0

### ZFW

0

### CG

0

### Fuel

0

### Cost index

0

### Route

0

### Location

0

### Agreement

- [X] Yes

**Comment by mclovin90** [comment] 2023-11-10 16:08
The Climb/Descent Forecast pages do not work at the moment, Dont think they have been coded in yet!

**Comment by GenericNerd** [comment] 2024-05-09 21:31
#11 has been updated to include this page. This is now a duplicate of that issue.

**Closed by GenericNerd** 2024-05-09 21:31 UTC
Labels: type: duplicate, sys: fms, type: todo
