### ISSUE TITLE
Plane accelerates after touchdown with ATS off

### ISSUE THREAD

**Issue by Thunderbird1337** [invernyx/md11-bugs#355] opened 2023-11-09 17:25 UTC
### Describe the bug

Thrust accelerates after touchdown with ATS off

### Steps to reproduce

As i disconnect the ATS and AP during Approach (via buttons on Joystick), i am able to control the plane by myself. After touchdown, the plane wants to accelerate by itself and ignores the thrustreverser input (F2; ATS still off in HSI screen). If i disengage AP via "AFS OVRD OFF", that bug wont happen.

### Expected behaviour

Plane shouldnt want to start again

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Departure

KDFW

### Arrival

KMIA

### Cruise level

FL410

### ZFW

280LBS

### CG

29%

### Fuel

52.8

### Cost index

80

### Route

KDFW/36R N0471F410 MRSSH3 ZALEA DCT SWB DCT HRV Q105 BLVNS Y290 GAWKS FROGZ4 KMIA/08R

### Location

runway

### Agreement

- [X] Yes

**Comment by KJA1582** [comment] 2023-11-09 18:06
+1, Stick Button displays ATS OFF in white but ATS remains on in the logic.

**Comment by TheFightingRaven** [comment] 2023-11-09 18:32
I believe this is part of the lowspeed protection triggering erroneously in approach and rollout

**Comment by Dennis380** [comment] 2023-11-10 14:35
Same here. You are able to decelerate the plane but you have to aggressivly press the Nosegear onto the Ground so the Plane can brake down! If oyu dont do that, the Plane will speed up by itself

**Comment by GenericNerd** [comment] 2023-11-13 19:09
Duplicate of #153

**Closed by GenericNerd** 2023-11-13 19:09 UTC
Labels: type: bug, type: duplicate, sys: autoflight
