### ISSUE TITLE
[BUG] - Selecting Automatic Anti-ice enables the digital stanby

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#563] opened 2023-11-16 01:37 UTC
### Describe the bug

When selecting Automatic Anti-Ice to enabled in the EFB, the digital standby will be enabled.

### Steps to reproduce

select automatic anti-ice to enabled

### Expected behaviour

should not enable the digital standby

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/10215076/edf99462-ff55-48b7-b864-c771a8be21af)

![image](https://github.com/invernyx/md11-bugs/assets/10215076/05dd231e-4787-4392-a2da-69d7e9e9562e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment] 2024-01-02 18:33
@turbofandude not sure if still valid. Was unable to reproduce... that is, standby instruments did not swap between digital and analog while enabling and disabling the auto ANTI-ICE system.

**Comment by turbofandude** [comment] 2024-01-02 18:53
This shouldn't be possible. Which variant (F or PAX) was this on?

**Comment by crazyforiphone** [comment] 2024-01-02 19:16
This was on the pax varient, just loaded in and it appears the issue is fixed.

**Comment by pburnay-invernyx** [comment] 2024-01-10 09:40
@turbofandude suggest closing this issue based on tests and feedback/confirmation received.

**Closed** 2024-01-29 18:10 UTC
Labels: type: bug, info: more info required, sys: supporting system
