### ISSUE TITLE
[BUG] - FMS shows wrong time of arrival

### ISSUE THREAD

**Issue by SamuelSamouris** [invernyx/md11-bugs#787] opened 2023-12-18 08:00 UTC
### Describe the bug

The FMS shows the wrong time or arrival to the destination airport

### Steps to reproduce

Setup the FMC
Begin flight

### Expected behaviour

I found that when I set up the fmc and began flying to my destination the time of arrival on the fmc was incorrect.

### Evidence

as you can see, even though the time is 22:38 the time of arrival at Shanghai is 2249 even though it’s 5170 miles away. On my flight plan it’s showing the time of arriving 0841Z.

it showed the time across the prog & FPLN page.

![195BD37653E840B8AD2AC2CD642A07B6](https://github.com/invernyx/md11-bugs/assets/65539593/65754068-5359-41b5-a5fa-b982dc9ea0bc)
![965CC89C19A04F2FA4207F091776B04B](https://github.com/invernyx/md11-bugs/assets/65539593/3ac5e473-47bd-4231-9b1e-63553993305f)
![C88D97C1384D483BB8ACA9833B758B1C](https://github.com/invernyx/md11-bugs/assets/65539593/d5593a7b-e08a-4c7d-a083-b968b91f8852)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL290

### Departure

EDDF

### Arrival

ZSSS

### Cruise level

FL290

### ZFW

182.5kg

### CG

17.7

### Fuel

93750kg

### Cost index

200

### Route

EDDF/18 SULUS4S SULUS Z650 VEMUT DCT PEMEL DCT DITIS DCT TOVKA DCT
ALAMU DCT BUD DCT BUDOP DCT IRLOX DCT STJ DCT DINRO N743 UDROS M859
KARDE N644 LAGAS M747 LUSAL N199 RASAM L88 METKA B476 DARVA B116
OGOLI N193 SR G134 TISIB L141 KAMUD W186 SADAN W187 TUSLI W112 BILDA
W619 CHW V67 YBL W199 NIRUV W220 TUTGO W218 APOGO B215 GODON W87 TYN
B208 HFE R343 SASAN SAS71A ZSSS/36R

copied from simbrief flightplan

### Location

This didn’t begin at a specific waypoint, but happened after takeoff.

### Agreement

- [X] Yes

**Comment by dr71205** [comment] 2023-12-18 16:11
#755 Likely same root cause

**Comment by turbofandude** [comment] 2024-02-07 18:00
Duplicate of https://github.com/invernyx/md11-bugs/issues/755

**Closed by turbofandude** 2024-02-07 18:00 UTC
Labels: type: bug, sys: fms
