### ISSUE TITLE
[BUG] - No Wingflex

### ISSUE THREAD

**Issue by absprouse23** [invernyx/md11-bugs#371] opened 2023-11-09 20:02 UTC
### Describe the bug

There is no wingflex while flying

### Steps to reproduce

Enter a normal flight and watch the wings; they are perfectly stiff

### Expected behaviour

Wings should bounce around as the aircraft rolls along the rough ground or through turbulent air.

### Evidence

https://youtu.be/T3W5x4rkjWs?si=5OOC0i0hrx9PGpaW&t=340

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment] 2024-01-02 09:29
This is a duplicate of [#408.](https://github.com/invernyx/md11-bugs/issues/408)

**Closed by arwasairl** 2024-01-02 09:29 UTC
Labels: sys: visual, type: todo
