### ISSUE TITLE
V-speed callouts 

### ISSUE THREAD

**Issue by espn74** [invernyx/md11-bugs#1122] opened 2024-04-26 17:01 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It would be nice to have callouts on take-off. 

### Describe alternatives you've considered

None

### Additional context

None

**Comment by slowreload** [comment] 2024-04-30 15:11
Second this

**Comment by Dimples82** [comment] 2024-05-01 18:27
IMO, if that is not an real life aircraft feature, no thanks.

**Comment by joon44** [comment] 2024-05-01 19:47
It could be an option in the efb

**Comment by espn74** [comment] 2024-05-01 20:52
> IMO, if that is not an real life aircraft feature, no thanks.

In the absence of a FO, is it more realistic to have a captain taking his eyes of the runway?

I think it is better to improve the experience for single pilot flights.

**Comment by TheFightingRaven** [comment] 2024-05-08 17:28
already planned

**Comment by GenericNerd** [comment] 2024-05-22 18:07
Duplicate of #598

**Closed by GenericNerd** 2024-05-22 18:07 UTC
Labels: type: todo, type: suggestion
