### ISSUE TITLE
[BUG] - Engine #1 and #3 do not start

### ISSUE THREAD

**Issue by Drocrvette** [invernyx/md11-bugs#361] opened 2023-11-09 18:41 UTC
### Describe the bug

when trying to start engines, only engine #2 starts, the other 2 engines, n2 does not rotate during startup. 

### Steps to reproduce

1. set the plane's state to "ready to start"
2. turn on apu air
3. try to start #1 or #3  
4. try to start #2

### Expected behaviour

n2 and n1 spool up before adding fuel

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48224503/e1f6d9c5-b2d0-4d05-8688-50527ad1bb5d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Sea level

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-09 18:43
work around for now, recycle the air system, the bug is there not in the engines

**Comment by Thunderbird1337** [comment] 2023-11-09 18:49
for transition:
toggle bleedsystem from auto to manual and back to auto b4 enginestart.
if this doesnt work, set the system to manual and open 1-2 and 1-3 isol valves.

PS: you should toggle all 4 systems (Hydraulic, Fuel, Electric, Bleed) auto-manual-auto to ensure, they are working in auto-mode

**Comment by GenericNerd** [comment] 2023-11-14 23:09
Likely caused by #247 which should be resolved by the next update. If it comes up after the next update, please open another issue and reference this issue (#361)

**Closed by GenericNerd** 2023-11-14 23:09 UTC
Labels: type: duplicate, sys: core
