### ISSUE TITLE
[BUG] - Not able to tune radios with BeyondATC or Logitech Flight Radio Panel

### ISSUE THREAD

**Issue by LKNprogrammer** [invernyx/md11-bugs#1279] opened 2024-05-28 20:12 UTC
### Describe the bug

When using BeyondATC, BeyondATC is not able to tune the radios of the MD11, like it can with every other aircraft.  The BATC devs say they are using standard SimConnect variables.  Also, when using AxisandOhs, and the Logitech Flight Panel, I am not able to control the radios either.

### Steps to reproduce

For BATC:

Launch BATC and utilize their program to attempt to change frequencies in the MD11 to a clearance, ground, tower, TRACON, or center frequency.

For Logitech Flight Radio Panel:

Utilizing the AxisandOhs tool, with the Saitek (Logitech Flight Radio Panel) option enabled, I am not able to tune the radios with the panel.  When loading in to other aircraft from other developers, this function works without any issues.

### Expected behaviour

I would expect that when using BATC, I would be able to auto-tune the radios of the MD11 using the BATC interface.

When using AxisandOhs, and the Logitech Flight Radio Panel, I would expect the standard SimConnect variables to work and allow me to control the NAV and COM radios in the MD11.  Otherwise, publish a list of variables that can be used by other developers to interface in to the MD11 Radio logic.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by slowreload** [comment] 2024-05-28 20:19
Also having issue with beyondatc have to manually tune the radio for it to work

**Comment by turbofandude** [comment] 2024-05-29 00:20
Duplicate of https://github.com/invernyx/md11-bugs/issues/547

**Closed by turbofandude** 2024-05-29 00:20 UTC
Labels: type: verification required, sys: supporting system
