### ISSUE TITLE
[BUG] - nosedive on short final

### ISSUE THREAD

**Issue by Jannik1211** [invernyx/md11-bugs#366] opened 2023-11-09 19:07 UTC
### Describe the bug

Aircraft points nose down abruptly after G/S is captured

### Steps to reproduce

Fly the ILS for runway 23 at EDDH using autoflight and wait for the G/S to intercept.

### Expected behaviour

It would follow the G/S and not push the nose all the way down without possibilities to recover. This happened when the gear was down already and I lowered the flaps to 35.

### Evidence

This is how it ended for me, on a 4nm final.
![image](https://github.com/invernyx/md11-bugs/assets/150371257/ce7c656b-bdfb-4331-8860-5bf2b3419bca)
![image](https://github.com/invernyx/md11-bugs/assets/150371257/bfcf5423-33a7-4ba3-9743-f1708005ecbc)

And I did not event have to do it again. The following streamer that I know had the same issue about 30 minutes later at the same position.
https://clips.twitch.tv/WealthyVivaciousPizzaRitzMitz-IrGjufz8ZT06K31v

You can compare it's roughly the same distance to the airport that I had. Refer to the houses and water nearby for position, but we had different speeds.
![image](https://github.com/invernyx/md11-bugs/assets/150371257/7e7d4a78-0428-441d-b0cf-bde0e2af9627)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-09 19:13
can you actually name your reports next time

**Comment by TheFightingRaven** [comment] 2023-11-09 19:40
https://clips.twitch.tv/WealthyVivaciousPizzaRitzMitz-IrGjufz8ZT06K31v

**Comment by Jannik1211** [comment] 2023-11-09 20:03
> can you actually name your reports next time

I thought I did, sorry. The other ones do have a name

**Comment by flymypi** [comment] 2023-11-10 15:37
can confirm, same happened to me on the ILS21 at EDFH right now

**Comment by Leemazz** [comment] 2023-11-12 18:51
Also had the same , left turn and nose dive with no control while capturing the glideslope . Happened at VIDP RWY28

**Comment by robcarlyh** [comment] 2023-11-13 20:42
Also had the same going in to EGNX last night

**Comment by turbofandude** [comment] 2023-11-14 23:45
I am digging into this but I am unable to reproduce this. I need more details or *exact* steps to get this to happen.

**Comment by davidnorfolk96** [comment] 2023-11-15 11:58
[LEPAEGKK_PDF_1700037369.pdf](https://github.com/invernyx/md11-bugs/files/13364241/LEPAEGKK_PDF_1700037369.pdf)
Had it on the newest build. Landed F35 with VAPP of 156. Real world weather. Captured the LOC then G/S onto 26L AP on. Hit around 3/4 NM from the runaway and nose went straight down. 

Note, i rounded up the fuel to 30000kg just in case i ran out.

**Comment by JDTiger** [comment] 2023-11-15 15:47
I had a nosedive on approach into LGAV on 2023-11-13, ILS-Z-03L after the autoland check.

Will have recordingsoftware running on every approach now, showing as much data as possible

**Comment by thisisraed** [comment] 2023-11-15 16:28
same thing happened just now
LFPG ILS APP RWY 27R
165 Vapp
Ap on, i had a really strong nosedive and completly lost controls

**Comment by Leemazz** [comment] 2023-11-18 10:01
Ok so i had this issue again on approach into YBTL RWY01 , approachd from the west captured the localiser between two hills , started to oscillate up and down switched the autopilot off and it was like it stalled with no response with imputs to the yoke . Also it did it twice but i think the second time was due to me starting the saved flight to low 
![Screenshot 2023-11-18 093757](https://github.com/invernyx/md11-bugs/assets/150618093/3b17362c-83fb-4e14-a32b-cbf5e416bbdb)
![Screenshot 2023-11-18 095459](https://github.com/invernyx/md11-bugs/assets/150618093/59deeddd-9ba0-417b-9759-2eecc03e56a9)

**Comment by kdries** [comment] 2023-11-19 23:17
Had the nose dive after the autoland check at Ivalo ILS22 around 4nm final.
Route: EFHK/22L N0472F400 DCT TEVRU Y75 NEPIX/N0476F410 DCT SOTIT SOTI3B EFIV/22

![image](https://github.com/invernyx/md11-bugs/assets/6001596/2fc05081-e979-4b87-a519-d37f714962a8)
![image](https://github.com/invernyx/md11-bugs/assets/6001596/920aef28-fcdd-4e78-9b47-7c18139b4169)

**Comment by turbofandude** [comment] 2023-11-20 21:32
We are still unable to reproduce this. The obvious and overwhelming evidence suggests it is indeed an issue with our code, we just pin it down. I saw in the linked video that the issue occurred immediately as LAND ARMED became DUAL LAND - is this consistent? Are you all seeing that same behavior?

**Comment by Jannik1211** [comment] 2023-11-20 22:08
> I saw in the linked video that the issue occurred immediately as LAND ARMED became DUAL LAND - is this consistent? Are you all seeing that same behavior?
For me yes. It happened right after DUAL LAND got active.

> Edit: Also, I see out of range CGs being cited as a possible cause - what is the CG at the time of the incident?
I am not sure about this, was the MD-11F without config, djb from discord reported the CG of it was outside the limits for the AP most likely.
Haven't had too much time to reproduce myself but it think it's possible this did it. 
I'll try to reproduce with the CG outside of limits, last flight I did with the MD-11F I did a couple of extra rounds around the airport just to make sure it wasn't anything with the DUAL LAND intercept Icame in a bit high, a bit low and right on, everything worked fine.

**Comment by CptUnicorn** [comment] 2023-11-22 01:56
Can confirm this happened to on final ILSZ 22R at KDTW. My CG at the time was 23.4. Gear down Flaps 35.

**Comment by Leemazz** [comment] 2023-11-24 09:50
After the first update flown around 10 flights with no issues on finals , MD flies real nice to be honest , just the weight issue

**Comment by Dennis380** [comment] 2023-12-02 13:11
Same happend to me a few Minutes ago. Was on Short Final on RWY02C WSSS (after an 13h flight) and the AP disconnected automatically so the AC started to nose dive. Recovery not possible. Even I gave TO/GA. The AC started to flip to the right and ditched into the water. Flight has been ended due to crash. This was my first flight after the newest Update. It didnt happend before. Just one more Time, right after Installation on the 9th of November. But then never again. I am slighty disappointed that this is still going to happen.

**Comment by GenericNerd** [comment] 2023-12-11 20:23
Potentially resolved in 0.21 and above (glad to have this closed finally!)

**Closed by GenericNerd** 2023-12-11 20:23 UTC
Labels: type: bug, type: unable to repro, sys: autoflight
