### ISSUE TITLE
 [BUG] - Aircraft stops responding randomly

### ISSUE THREAD

**Issue by sersanchez** [invernyx/md11-bugs#369] opened 2023-11-09 19:56 UTC
### Describe the bug

Cannot click on anything

### Steps to reproduce

I have tried 2 flights in the MD11. Both had the same issue.
First flight, KDFW to KBOS. Pax airplane. Default white livery. I started descending and when I passed 15000ft, everything stopped responding. The hand cursor still shows, but clicking on heading, Nav, or even the speedbreak, had no effect. Nothing worked. The plane eventually crashed into the ocean and when it bounced back, I had control of the yoke but not the throttles. Gear handle or flaps didnt work either.

Second flight, again KDFW to KBOS, Cargo version, UPS livery. This time, when I was configuring the MCDU entering waypoints, everything stopped responding again. Flaps, throttle, yoke, nothing moves

### Expected behaviour

I would expect to be able to manipulate things inside the cockpit

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-09 20:06
wasm crash, should be fixed when the aircraft is reloaded, are looking to see if we can find the causes

**Comment by sersanchez** [comment] 2023-11-09 20:38
Just happened again... :-(

**Comment by flymypi** [comment] 2023-11-09 23:07
can confirm this

**Comment by dodoactual** [comment] 2023-11-10 02:35
Selecting a LSK associated with a DISCO/END in FPLN menu caused this issue once so far

**Comment by JF1997** [comment] 2024-01-27 12:05
Hello, adding on a report for this. Flew from Memphis to Oakland tabbed into the simulator but not actively touching anything as I was using my work laptop at the time and looked over to see the aircraft in a right bank and descending but the aircraft displays were frozen showing straight and level flight at cruise and the ND was stable. Autopilot no longer worked so I quit the flight. Route was: ZUMIT5 FOXOM DCT TUL/N0479F400 DCT KK42C DCT KK45A DCT KD48Y DCT PUB DCT KD51U DCT BUGGG DCT KU51O DCT KU51M DCT KU51K DCT JSICA DCT MONOH OAKES2 and the OFP can be found here: https://www.simbrief.com/ofp/flightplans/KMEMKOAK_PDF_1706300831.pdf

**Closed** 2024-04-05 20:36 UTC
Labels: type: bug
