### ISSUE TITLE
In flight spoiler use causing massive pitch down moment.

### ISSUE THREAD

**Issue by FelixFeltersnatch** [invernyx/md11-bugs#597] opened 2023-11-18 22:49 UTC
### Describe the bug

When using the spoiler to decelerate the aircraft on arrival, the Flight Director cue immediately pitches down when using spoilers inflight to manage energy. This, in turn, cause a very noticeable downward pitching moment. 

### Steps to reproduce

In managed speed mode (FMS Speed) while descending, use the in-flight spoilers to manage your energy.

### Expected behaviour

Pitch stays relatively the same while the aircraft decelerates.

### Evidence

https://imgur.com/HfCPAr5

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment] 2023-11-19 09:16
Sometimes taking spoilers out, the ATS increases thrust a lot while still flying much faster than the speed target.

**Comment by turbofandude** [comment] 2024-05-27 19:39
Duplicate of https://github.com/invernyx/md11-bugs/issues/207 and will be fixed by FD improvements.

**Closed by turbofandude** 2024-05-27 19:39 UTC
Labels: type: bug, sys: flight dynamics
