### ISSUE TITLE
[BUG] - Incorrect ground speed indication

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#483] opened 2023-11-12 00:37 UTC
### Describe the bug

After landing the ground speed indications on ND and PFD are too high. Noticeable especially after longer flight. Additionally, there appears to be small discrepancy between GS indications on ND and PFD.

### Steps to reproduce

Check ground speed indications after landing.

### Expected behaviour

Indicated ground speed should be closer to the actual ground speed

### Evidence

![Näyttökuva 2023-11-12 015857](https://github.com/invernyx/md11-bugs/assets/150369113/87866918-59ca-4a82-ab4f-3eb390775a23)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [x] Yes

**Comment by turbofandude** [comment] 2023-11-17 22:21
This was caused by an EXTREMELY overactive residual groundspeed system. I've reduced this - that said, realigning the IRU after a long flight is recommended due to position drift and accumulated speed error (which we simulate). Otherwise, fixed in 0.13+.

**Closed by turbofandude** 2023-11-17 22:21 UTC
Labels: type: bug, sys: displays
