### ISSUE TITLE
[BUG] - SMOKE IN THE COCKPIT!

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#632] opened 2023-11-22 17:47 UTC
### Describe the bug

Clouds intrude into the cockpit as you fly through them.

### Expected behaviour

To not have clouds intrude into the cockpit as you fly through them.

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1Fdw8EpX0rsFmf/d13373CXVU7s?invite=cr-MSw1UTEsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment] 2023-11-22 17:57
Duplicate... see PR #520

**Comment by arwasairl** [comment] 2024-01-02 09:17
Duplicate of [#520](https://github.com/invernyx/md11-bugs/issues/520). Will be closed.

**Closed by arwasairl** 2024-01-02 09:17 UTC
Labels: type: bug, sys: visual
