### ISSUE TITLE
[BUG] - can't change radio atc frequency on fs radio panel

### ISSUE THREAD

**Issue by AlexXx88** [invernyx/md11-bugs#547] opened 2023-11-15 14:18 UTC
### Describe the bug

can't change radio atc frequency on fs radio panel

### Steps to reproduce

start a flight, ghive electricity at the plane and try use fs atc panel

### Expected behaviour

change frequency and use corectly the flight sim integrated atc panel

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/104494440/0e719ec6-9cbb-4244-ba1c-d42b9c5e8092)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by alxcpt** [comment] 2023-11-15 19:26
Additional info:
you can select a frequency via fs atc panel but it isn't shown in the VHF standby window, sometimes weird flickering happening. If you select the frequency via VHF you can use the atc normally until next freq change.
https://github.com/invernyx/md11-bugs/assets/150608109/a7c8b13b-d66a-470f-b86e-ab7924a19269

**Comment by TheFightingRaven** [comment] 2023-11-15 21:41
@turbofandude allow the in sim atc panel to set the radio

**Comment by turbofandude** [comment] 2023-11-17 20:02
@pburnay-invernyx We need to change the value to only write when changed by our knobs and otherwise, read from the value in the sim

**Comment by KJA1582** [comment] 2024-05-28 22:43
If not already done, syncing the internal standby frequency with

COM1 STORED FREQUENCY (COM2 and COM3 resp.)

should be done as well to ensure consitency

Ref: https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#com

**Comment by LKNprogrammer** [comment] 2024-05-29 14:41
So I opened issue #1279 and it was closed as saying it was a duplicate of this issue.  So, ultimately what is the disposition of the issue?  Is the behavior going to be changed in the MD11 or not as it relates to the ability to set the frequencies on the NAV and COM radios outside the cockpit without using a mouse?  I am just looking for some clarification.

**Comment by turbofandude** [comment] 2024-05-30 19:10
Resolved in 0.56+

**Closed by turbofandude** 2024-05-30 19:10 UTC
Labels: sys: core, type: todo
