### ISSUE TITLE
[BUG] - mcp altitude window cuts off value

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#20] opened 2023-08-14 22:38 UTC
### Describe the bug

mcp values cut off at the top, now also present for overhead fuel indicators

### Expected behaviour

to not cut off

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2023-11-02 00:16
Duplicate of #18

**Closed by GenericNerd** 2023-11-02 00:16 UTC
Labels: type: bug, type: duplicate, sys: visual
