### ISSUE TITLE
[BUG] - Turning off displays removes data

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#1036] opened 2024-04-10 16:34 UTC
### Describe the bug

When turning displays off some of the displayed data is lost.

### Expected behaviour

No data is lost when turning displays off and back on.

### Evidence

https://www.youtube.com/watch?v=H7ziTIKeF_w
![image](https://github.com/invernyx/md11-bugs/assets/6001596/2f431105-615f-4071-b522-c5f2b45067c4)
![image](https://github.com/invernyx/md11-bugs/assets/6001596/e4a6a40f-7903-4c9d-9710-07b4183f9d00)
![image](https://github.com/invernyx/md11-bugs/assets/6001596/a1df776d-4285-41f9-9821-18d283ed2d3b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2024-04-10 22:51
Duplicate of #931

**Closed by GenericNerd** 2024-04-10 22:51 UTC
Labels: type: duplicate, sys: displays
