### ISSUE TITLE
[BUG] FPLN INIT Resets after inputting F-PLN

### ISSUE THREAD

**Issue by KevinDClaus** [invernyx/md11-bugs#570] opened 2023-11-16 16:47 UTC
### Describe the bug

when inputting data during preflight, after the F-PLN page was completed the PERF was in DES and the TO/APPR was showing the approach only. Going back to the INIT page at this point reset all data that was already inputted.

### Steps to reproduce

On the ground @ KORD, cold and dark at the FedEx ramp
powered on the aircraft and turned on the IRS 1 AUX 2
INIT page for a flight from KORD to KMEM as FDX610, FL630, -52/TL16, CI40
weights were generated from the aircraft
F-PLN page set up for a departure off of 28C, there are no SIDS for KORD so just runway
route as follows: CMSKY CARYN CYBIL PXV
at this point going into the PERF page brings up VNAV climb and TO/APPR brings up options for the KORD Takeoff 28R
Go back to F-PLN and input the BLUZZ3 PXV STAR and the ILS36L approach
at thing point you go to PERF and DES appears and TO/APPR populates with the approach
going back to INIT erases all data that has been entered, but the IRS remains alligned

### Expected behaviour

Even if there is no SID inputted I would expect the TO page to be visible, and then going back to the INIT page all data inputted should still be there

### Evidence

The two possibilities I have yet to isolate at the moment:
Scenery issue where the aircraft thinks it is in the air when on the ground
The airport not having any SIDS can be affecting what pages the MCDU is allowing to be viewed

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Departure

KORD

### Arrival

KMEM

### Cruise level

FL360

### ZFW

248.6

### CG

24.6

### Fuel

53.7

### Cost index

40

### Route

KORD28R
CMSKY
CARYN
CYBIL
PXV
BLUZZ3.PXV
KMEM36L

### Location

KORD, FedEx ramp spot 4 parked

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-16 20:23
duplicate of #540

**Closed by TheFightingRaven** 2023-11-16 20:23 UTC
Labels: type: duplicate, type: verification required, sys: fms
