### ISSUE TITLE
[BUG] - P3D5 - Mouse interaction with switches / handles

### ISSUE THREAD

**Issue by balint221** [invernyx/md11-bugs#825] opened 2023-12-31 13:37 UTC
### Describe the bug

Scrolling up or down on the middle mouse button only increases the selection on the Speed brake lever.

### Expected behaviour

Scrolling up or down on the middle wheel should increase or decrease the lever / switch position instead of cycling through all the position until it gets back to its start / default position.

### Evidence

For example, scroll DOWN (or UP) on the speed brake lever and the speed brake will extend as expected. However, reverse the scroll to UP and the speed brake lever continues to extend no matter the scroll wheel direction. 
This issue also applies to left clicking on the speed brake lever. Left click and the speed brake will extend by increments as expected. Right click and the speed brake will continue to extend INSTEAD of retracting. Also there is no click spot or any way to arm the speed brake.

### Simulator

P3Dv5

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2024-05-29 19:33
Duplicate of #336

**Closed by GenericNerd** 2024-05-29 19:33 UTC
Labels: type: bug, type: duplicate, sys: visual
