### ISSUE TITLE
[BUG] - Severe lateral oscillations approaching waypoint

### ISSUE THREAD

**Issue by opticalgenesis** [invernyx/md11-bugs#224] opened 2023-10-28 17:22 UTC
### Describe the bug

On the DOTSS2.CLEEE KLAX.24L, when approaching NAANC from ENNEY the FDs and AP can be seen to wobble on the roll axis noticeably

### Steps to reproduce

- Fly the KLAX.24L DOTSS2.CLEEE SID
- Have automation on after ENNEY but before NAANC

### Expected behaviour

- No oscillations along lateral axis

### Evidence

Will be in Teams -- 10 s ish into the video

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

KLAX

### Arrival

KJFJ

### Cruise level

10000B

### ZFW

227.7 lbs

### CG

28.2

### Fuel

81.4 lbs

### Cost index

20

### Route

KLAX/24R N0474F370 DOTSS2 CLEEE DCT PKE DCT DRK J96 CIM/N0473F390 J96 SLN J24 MCI J80 SPI DCT KOLTS DCT WWODD DCT RINTE DCT KLYNE Q29 WWSHR DCT JHW J70 LVZ LENDY6 KJFK/31L

### Location

Between ENNEY and NAANC

### Agreement

- [X] Yes

**Comment by turbofandude** [comment] 2023-10-31 21:27
I believe I have identified the cause of this and it should be resolved in 0.9.0.

**Closed** 2023-11-01 00:21 UTC
Labels: verification required, autoflight
