### ISSUE TITLE
Nosewheel cocked 90 degrees on power-up

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1232] opened 2024-05-26 02:32 UTC
### Describe the bug

Nosewheel cocked 90 degrees on power-up

### Expected behaviour

Nose wheel should always be centered at the gate.

### Evidence

![Screenshot 2024-05-24 181405](https://github.com/invernyx/md11-bugs/assets/148719444/b01aed6e-e6b9-4b94-b71f-b6f332152433)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by Mets747** [comment] 2024-05-26 16:16
+1

**Comment by FelixFeltersnatch** [comment] 2024-05-27 02:19
+1

**Comment by GenericNerd** [comment] 2024-05-27 16:51
Duplicate of #1219

**Closed by GenericNerd** 2024-05-27 16:51 UTC
Labels: type: duplicate, sys: displays
