### ISSUE TITLE
[BUG] - EFB can display negative load

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1257] opened 2024-05-27 19:20 UTC
### Describe the bug

EFB can display a negative failure in "load" or "Payload"

### Expected behaviour

Negative values don't make any sense on this. 

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/7919184/868aa558-22a6-4869-a6b5-a8f48e96dfdb)
![image](https://github.com/invernyx/md11-bugs/assets/7919184/218d547e-08a8-4107-a09a-33f8d12294f0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2024-05-27 19:48
Duplicate of #1209

**Closed by GenericNerd** 2024-05-27 19:48 UTC
Labels: type: duplicate, sys: displays
