### ISSUE TITLE
[BUG] - EFB. Unable to pan around when entering the cargo field in the payload screen 

### ISSUE THREAD

**Issue by sersanchez** [invernyx/md11-bugs#451] opened 2023-11-11 13:05 UTC
### Describe the bug

I am unable to pan around the aircraft when I enter the Cargo field in the EFB

### Steps to reproduce

When in the cargo version, click into the Cargo box in the payload manager. Then try to pan around to see other stuff in the cockpit

### Expected behaviour

I should be able to move around when the cargo box is selected

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

600ft

### Departure

KAFW

### Arrival

KMEM

### Cruise level

FL350

### ZFW

61.2

### CG

31%

### Fuel

12.2

### Cost index

25

### Route

No route yet. Still in preflight

### Location

KAFW Cargo ramp

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-13 19:12
blocking panning inputs instead of keyboard

**Comment by GenericNerd** [comment] 2023-11-14 11:45
Duplicate of #330

**Closed by GenericNerd** 2023-11-14 11:45 UTC
Labels: type: duplicate, sys: fms
