### ISSUE TITLE
[BUG] - Standby Analog Altimeter not working proberly

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#555] opened 2023-11-15 17:47 UTC
### Describe the bug

The sand by altimeter and speed tape does not match what is on the PFDs.

### Expected behaviour

The main dial is stuck at -10000ft and does not move. The needle moves when adjusting the pressure, but it will also jump around erratically. The actual altimeter numbers both MB and IN HG are not true measurements of each. See photos and video.

### Evidence

https://imgur.com/pzG3UdN
https://medal.tv/games/microsoft-flight-simulator/clips/1DXUtVLIHRVvg9/d1337Z8UwlGu?invite=cr-MSxjUEIsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment] 2023-11-15 21:49
duplicate of #218 and #305

**Closed by TheFightingRaven** 2023-11-15 21:49 UTC
Labels: type: wontfix, type: verification required, sys: displays
