### ISSUE TITLE
[BUG] - Display information disappears when turning displays on and off

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1201] opened 2024-05-23 12:47 UTC
### Describe the bug

Some information on the displays disappear when turning displays on and off.

### Expected behaviour

For all information to remain.

### Evidence

https://www.youtube.com/watch?v=t7c9RE4RhTU

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2024-05-23 14:37
Duplicate of #931

**Closed by GenericNerd** 2024-05-23 14:37 UTC
Labels: type: duplicate, sys: displays
