### ISSUE TITLE
TCAS Test not working 

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#459] opened 2023-11-11 22:59 UTC
### Describe the bug

Upon pressing the TCAS Test button, no test-loop is performed. 

### Steps to reproduce

Press TCAS Test 

### Expected behaviour

Display and audio test indication. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2023-12-06 23:03
Duplicate of #276

**Closed by GenericNerd** 2023-12-06 23:03 UTC
Labels: type: duplicate, sys: core
