### ISSUE TITLE
Total system freeze following a DIR TO input on the FMC

### ISSUE THREAD

**Issue by Kbye123** [invernyx/md11-bugs#91] opened 2023-10-22 15:09 UTC
### Describe the bug

Total system freeze following a DIR TO input on the FMC

### Steps to reproduce

Decided to divert to EGCC so did a DIR TO- EGCC command. FMC went blank and all systems became unresponsive. Aircraft would respond to key inputs only and all animations worked fine. 

### Expected behaviour

Nav response and new route/magenta line.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

25000

### Departure

EGDM

### Arrival

EGCC

### Cruise level

400

### ZFW

?

### CG

?

### Fuel

14.5

### Cost index

99

### Route

Can't recall

### Location

Overhead EGVN at the time. 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment] 2023-10-24 18:54
DIR TO behavior does work as intended. Without knowing what route you were using and what leg you were on, I cannot recreate this. As a result, I will be closing this out as invalid. Please re-open with more details if it happens again and we will get it resolved.

**Closed by turbofandude** 2023-10-24 18:54 UTC
Labels: verification required, fms
