### ISSUE TITLE
[BUG] - Aircraft circling a fly-past waypoint on SID

### ISSUE THREAD

**Issue by opticalgenesis** [invernyx/md11-bugs#215] opened 2023-10-28 13:59 UTC
### Describe the bug

Flying the RUS9YD SID from ZBAA, sequence AA451->AA453->AA454, the ND draws AA453 as a fly-past point. Upon passing AA451 the aircraft did not fly the magenta line and instead flew directly towards AA453. It then began circling around AA453, never sequencing to the next waypoint, nor showing any deviation left or right of magenta line

### Steps to reproduce

- Load route departing from ZBAA
  - This case was ZBAA/VHHX
- Enter the RUS9YD SID
- Upon reaching AA451, observe the aircraft disregarding magenta line guidance

### Expected behaviour

- To fly past AA453 and continue en-route

### Evidence

Will be in Teams

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

ZBAA

### Arrival

VHHX

### Cruise level

FL340

### ZFW

294.3 lbs

### CG

36.4

### Fuel

63.7 lbs

### Cost index

200

### Route

ZBAA/36R K0898S1220 RUS9YD RUSDO W45 SQ/K0906S1250 B208 CGO W129 KAMDA/K0907S1220 V109 LKO A461 LIG/K0898S1250 R473 BEMAG/K0900S1220 V5 CON R473 POU TAMT31 VHHX/31

### Location

AA453 on the SID

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2023-11-02 00:10
Duplicate of #217 (now fixed)

**Closed by GenericNerd** 2023-11-02 00:10 UTC
Labels: type: bug, type: duplicate, sys: autoflight
