### ISSUE TITLE
[BUG] - GEN LOAD HI bug

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1072] opened 2024-04-14 19:48 UTC
### Describe the bug

GEN LOAD HIGH emssage on EAD but the gen load is normal

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

![Screenshot 2024-04-14 214532](https://github.com/invernyx/md11-bugs/assets/71586114/b7f51926-0ea5-4515-bbb7-373b7ef67ad5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2024-04-15 21:19
Duplicate of #213

**Closed by GenericNerd** 2024-04-15 21:19 UTC
Labels: type: duplicate, sys: core
