### ISSUE TITLE
[BUG] - values cutting off

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#112] opened 2023-10-25 10:48 UTC
### Describe the bug

values on the autopilot and fuel panel are being cut off

### Steps to reproduce

always

### Expected behaviour

not to do this

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/77b8cd67-ac7d-4d3f-9904-2edc7efba2cc)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/d9bf5f86-4fca-4724-8f32-87866c7abd82)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment] 2023-11-02 00:17
Duplicate of #18

**Closed by GenericNerd** 2023-11-02 00:17 UTC
Labels: type: bug, type: duplicate, sys: displays
